config/routes.rb
Rails.application.routes.draw do
  get 'doses/index'
  get 'doses/new'
  get 'doses/create'
  get 'doses/edit'
  get 'doses/update'
  get 'doses/destroy'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :cocktails
  resources :ingredients
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cocktail.rb
class Cocktail < ApplicationRecord
  has_many :doses, dependent: :destroy
  validates :name, uniqueness: true
end

app/models/dose.rb
class Dose < ApplicationRecord
  belongs_to :cocktail #, class_name: "Cocktail", foreign_key: "cocktail_id"
  belongs_to :ingredient #, class_name: "Ingredient", foreign_key: "ingredient_id"
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  has_many :doses, dependent: :destroy
  validates :name, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cocktails_controller.rb
class CocktailsController < ApplicationController
  def index
    @cocktails = Cocktail.all
  end

  def show
    @cocktail = Cocktail.find(params["id"])
    @doses = Dose.where(cocktail_id: params["id"])
  end

  def new
    @cocktail = Cocktail.new
    @dose = Dose.new
  end

  def create
    @cocktail = Cocktail.new(cocktail_params)
    @cocktail.valid? ? @cocktail.save : "" #redirect_to new_cocktail_path

    redirect_to cocktails_path
  end

  def edit
    @cocktail = Cocktail.find(params[:id])
  end

  def update
    @cocktail = Cocktail.find(params[:id])
    @cocktail.update(cocktail_params)
    # @cocktail.save

    redirect_to cocktails_path
  end

  def destroy
    this_cocktail = Cocktail.find(params[:id])
    this_cocktail.destroy
    redirect_to cocktails_path
  end

  private

  def cocktail_params
    params.require(:cocktail).permit(:name)
  end

end

app/controllers/doses_controller.rb
class DosesController < ApplicationController
  def index
    @doses = Dose.where("cocktail_id = ?", params[:cocktail_id])
    @cocktail = Cocktail.find(params[:cocktail_id])
  end

  def new
  end

  def create
  end

  def edit
  end

  def update
  end

  def destroy
  end
end

app/controllers/ingredients_controller.rb
class IngredientsController < ApplicationController
  def index
    @ingredients = Ingredient.all
  end

  def new
    @ingredient = Ingredient.new
  end

  def create
    @ingredient = Ingredient.new(ingredient_params)
    @ingredient.valid? ? @ingredient.save : "" #redirect_to new_cocktail_path

    redirect_to ingredients_path
  end

  def edit
    @ingredient = Ingredient.find(params[:id])
  end

  def update
    @ingredient = Ingredient.find(params[:id])
    @ingredient.update(ingredient_params)
    # @cocktail.save

    redirect_to ingredients_path
  end

  def destroy
    this_ingredient = Ingredient.find(params[:id])
    this_ingredient.destroy
    redirect_to ingredients_path
  end

  private

  def ingredient_params
    params.require(:ingredient).permit(:name, :ingredient, :quantity)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cocktails_helper.rb
module CocktailsHelper
end

app/helpers/doses_helper.rb
module DosesHelper
end

app/helpers/ingredients_helper.rb
module IngredientsHelper
end

app/views/cocktails/_form.html.erb
<%= form_for(@cocktail, @dose) do |f| %>
  <%= hidden_field_tag :authenticity_token, form_authenticity_token %>
  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.submit %>

<% end %>

app/views/cocktails/edit.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>Document</title>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.1.0/css/all.css" integrity="sha384-lKuwvrZot6UHsBSfcMvOkWwlCMgc0TaWr+30HWe3a4ltaBwTZhyTEggF5tJv8tbt" crossorigin="anonymous">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/css/bootstrap.min.css" integrity="sha384-rwoIResjU2yc3z8GV/NPeZWAv56rSmLldC3R/AZzGRnGxQQKnKkoFVhFQhNUwEyJ" crossorigin="anonymous">

</head>
<body>
  <div class="container">
    <h1>Cocktails#edit</h1>
    <p>Find me in app/views/cocktails/edit.html.erb</p>

    <%= render 'form', cocktail: @cocktail %>

    <%= link_to "Return", cocktail_path%>

    <p>
      <%= link_to "Return to the cocktail list", cocktails_path%>
    </p>
  </div>
</body>
</html>

app/views/cocktails/index.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>Document</title>
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.1.0/css/all.css" integrity="sha384-lKuwvrZot6UHsBSfcMvOkWwlCMgc0TaWr+30HWe3a4ltaBwTZhyTEggF5tJv8tbt" crossorigin="anonymous">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/css/bootstrap.min.css" integrity="sha384-rwoIResjU2yc3z8GV/NPeZWAv56rSmLldC3R/AZzGRnGxQQKnKkoFVhFQhNUwEyJ" crossorigin="anonymous">

</head>
<body>
<div class="container">
  <h1>Cocktails#index</h1>
  <p>Find me in app/views/cocktails/index.html.erb</p>

  <p>
    <%= link_to new_cocktail_path do %>
    <i class="fas fa-plus"></i> Add a new cocktail
    <% end %>
  </p>
  <p>
    <%= link_to ingredients_path do %>
    <i class="far fa-eye"></i> See the ingredient list
    <% end %>
  </p>

  <% @cocktails.each do |cocktail| %>

  <div class="one-cocktail">
      <%= link_to cocktail.name, cocktail_path(cocktail) %>
      <%= link_to cocktail_path(cocktail), method: :delete, data:{confirm: "Delete this cocktail?"} do %><i class="far fa-trash-alt"></i><% end %>
  </div>
  <% end %>
</div>

</body>
</html>

app/views/cocktails/new.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>Document</title>
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.1.0/css/all.css" integrity="sha384-lKuwvrZot6UHsBSfcMvOkWwlCMgc0TaWr+30HWe3a4ltaBwTZhyTEggF5tJv8tbt" crossorigin="anonymous">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/css/bootstrap.min.css" integrity="sha384-rwoIResjU2yc3z8GV/NPeZWAv56rSmLldC3R/AZzGRnGxQQKnKkoFVhFQhNUwEyJ" crossorigin="anonymous">

</head>
<body>
  <div class="container">
    <h1>Cocktails#new</h1>
    <p>Find me in app/views/cocktails/new.html.erb</p>

    <%= render 'form', cocktail: @cocktail %>

    <%= link_to "Return to the cocktail list", cocktails_path%>
  </div>
</body>
</html>

app/views/cocktails/show.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>Document</title>
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.1.0/css/all.css" integrity="sha384-lKuwvrZot6UHsBSfcMvOkWwlCMgc0TaWr+30HWe3a4ltaBwTZhyTEggF5tJv8tbt" crossorigin="anonymous">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/css/bootstrap.min.css" integrity="sha384-rwoIResjU2yc3z8GV/NPeZWAv56rSmLldC3R/AZzGRnGxQQKnKkoFVhFQhNUwEyJ" crossorigin="anonymous">

</head>
<body>
  <div class="container">
    <h1>Cocktails#show</h1>
    <p>Find me in app/views/cocktails/show.html.erb</p>

    <h2><%= @cocktail.name %></h2>

    <% @doses.each do |dose| %>
    <p><%= dose.ingredient.name %> (<%= dose.quantity %>)</p>
    <% end %>

    <%= link_to edit_cocktail_path(@cocktail) do %>
    <i class="far fa-edit"></i><i class="fas fa-cocktail"></i> Edit
    <% end %>

    <%= link_to cocktail_path(@cocktail), method: :delete, data:{confirm: "Delete this cocktail?"} do %><i class="far fa-trash-alt"></i> Delete<% end %>
    <p><%= link_to "Return to the cocktail list", cocktails_path%></p>
  </div>

</body>
</html>

app/views/doses/edit.html.erb
<h1>Doses#edit</h1>
<p>Find me in app/views/doses/edit.html.erb</p>

app/views/doses/index.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>Document</title>
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.1.0/css/all.css" integrity="sha384-lKuwvrZot6UHsBSfcMvOkWwlCMgc0TaWr+30HWe3a4ltaBwTZhyTEggF5tJv8tbt" crossorigin="anonymous">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/css/bootstrap.min.css" integrity="sha384-rwoIResjU2yc3z8GV/NPeZWAv56rSmLldC3R/AZzGRnGxQQKnKkoFVhFQhNUwEyJ" crossorigin="anonymous">

</head>
<body>
  <div class="container">
    <h1>Doses#index</h1>
    <p>Skip the cocktail show</p>

    <h2><%= @cocktail.name %></h2>

    <% @doses.each do |dose| %>
    <ul><%= dose.ingredient.name %>: <%= dose.quantity %></ul>
    <% end %>

    <p><%= link_to "Return to the cocktail list", cocktails_path%></p>
  </div>

</body>

app/views/doses/new.html.erb
<h1>Doses#new</h1>
<p>Find me in app/views/doses/new.html.erb</p>

app/views/ingredients/_form.html.erb
<%= form_for(@ingredient) do |f| %>
  <%= hidden_field_tag :authenticity_token, form_authenticity_token %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.submit %>
<% end %>

app/views/ingredients/edit.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>Document</title>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.1.0/css/all.css" integrity="sha384-lKuwvrZot6UHsBSfcMvOkWwlCMgc0TaWr+30HWe3a4ltaBwTZhyTEggF5tJv8tbt" crossorigin="anonymous">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/css/bootstrap.min.css" integrity="sha384-rwoIResjU2yc3z8GV/NPeZWAv56rSmLldC3R/AZzGRnGxQQKnKkoFVhFQhNUwEyJ" crossorigin="anonymous">

</head>
<body>
  <div class="container">
    <h1>Ingredients#edit</h1>
    <p>Find me in app/views/ingredients/edit.html.erb</p>
    <%= render 'form', ingredient: @ingredient %>
    <p><%= link_to "Return to the ingredient list", ingredients_path%></p>
  </div>
</body>
</html>

app/views/ingredients/index.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>Document</title>
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.1.0/css/all.css" integrity="sha384-lKuwvrZot6UHsBSfcMvOkWwlCMgc0TaWr+30HWe3a4ltaBwTZhyTEggF5tJv8tbt" crossorigin="anonymous">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/css/bootstrap.min.css" integrity="sha384-rwoIResjU2yc3z8GV/NPeZWAv56rSmLldC3R/AZzGRnGxQQKnKkoFVhFQhNUwEyJ" crossorigin="anonymous">

</head>
<body>
<div class="container">
  <h1>Ingredients#index</h1>
  <p>Find me in app/views/ingredients/index.html.erb</p>

  <p>
    <%= link_to new_ingredient_path do %>
    <i class="fas fa-plus"></i> Add a new ingredient
    <% end %>
  </p>

  <p>
    <%= link_to cocktails_path do %>
    <i class="far fa-eye"></i> Return to the cocktail list
    <% end %>
  </p>

  <% @ingredients.each do |ingredient| %>
  <ul>
      <%= ingredient.name %>
      <%= link_to ingredient_path(ingredient), method: :delete, data:{confirm: "Delete this ingredient?"} do %><i class="far fa-trash-alt"></i>
          <%= link_to edit_ingredient_path(ingredient) do %>
            <i class="far fa-edit"></i>
          <% end %>
      <% end %>
  </ul>
  <% end %>

</div>

</body>
</html>

app/views/ingredients/new.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>Document</title>
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.1.0/css/all.css" integrity="sha384-lKuwvrZot6UHsBSfcMvOkWwlCMgc0TaWr+30HWe3a4ltaBwTZhyTEggF5tJv8tbt" crossorigin="anonymous">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/css/bootstrap.min.css" integrity="sha384-rwoIResjU2yc3z8GV/NPeZWAv56rSmLldC3R/AZzGRnGxQQKnKkoFVhFQhNUwEyJ" crossorigin="anonymous">

</head>
<body>
  <div class="container">
    <h1>Ingredients#new</h1>
    <p>Find me in app/views/ingredients/new.html.erb</p>

    <%= render 'form', ingredient: @ingredient %>

    <%= link_to "Return to the ingredient list", ingredients_path%>
  </div>
</body>
</html>

app/views/layouts/_footer.html.erb
<div class="footer">
  <div class="footer-links">
    <a href="#"><i class="fab fa-github"></i></a>
    <a href="#"><i class="fab fa-instagram"></i></a>
    <a href="#"><i class="fab fa-facebook"></i></a>
    <a href="#"><i class="fab fa-twitter"></i></a>
    <a href="#"><i class="fab fa-linkedin"></i></a>
  </div>
  <div class="footer-copyright">
    This footer is made with <i class="fa fa-heart"></i> at Le Wagon
  </div>
</div>

app/views/layouts/_navbar.html.erb
<div class="navbar-wagon">
  <!-- Logo -->
  <a href="/" class="navbar-wagon-brand">
    <img src="images/logo.png" alt="logo">
  </a>

  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">

    <a href="" class="navbar-wagon-item navbar-wagon-link">Host</a>
    <a href="" class="navbar-wagon-item navbar-wagon-link">Trips</a>
    <a href="" class="navbar-wagon-item navbar-wagon-link">Messages</a>

    <!-- Profile picture with dropdown list -->
    <div class="navbar-wagon-item">
      <div class="dropdown">
        <img src="https://kitt.lewagon.com/placeholder/users/ssaunier" class="avatar dropdown-toggle" id="navbar-wagon-menu" data-toggle="dropdown">
        <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
          <li><a href="#">Profile</a></li>
          <li><a href="#">Dashboard</a></li>
          <li><a href="#">Log Out</a></li>
        </ul>
      </div>
    </div>
  </div>

  <!-- Dropdown appearing on mobile only -->
  <div class="navbar-wagon-item hidden-md hidden-lg">
    <div class="dropdown">
      <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
        <li><a href="#">Host</a></li>
        <li><a href="#">Trips</a></li>
        <li><a href="#">Messagese</a></li>
      </ul>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsMisterCocktail</title>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.1.0/css/all.css" integrity="sha384-lKuwvrZot6UHsBSfcMvOkWwlCMgc0TaWr+30HWe3a4ltaBwTZhyTEggF5tJv8tbt" crossorigin="anonymous">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>


  <body>
    <%= render partial: "layouts/navbar" %>
    <%= yield %>
    <%= render partial: "layouts/footer" %>
  </body>
</html>